### ISSUE TITLE
can't set data on dexterity objects

### ISSUE THREAD

**Issue by djay** [collective/rapido.plone#22]
# User problem

Dexterity requires attribute setting to work. For example ```obj.title = "blah"```. RestrictedPython prevents this as it allows you to replace code (and possibly other reasons).

# Options

- DX should provide a generic update(title=...) method to provide another way to update any schema field similar to AT.
   - con: 2 apis for doing the same thing. incosistent docs.
- Rapido could have a smarter guard of setting attributes which looks to see if attribute is part of a schema and allows it in such cases. Could also do some security checks?

**Comment by ebrehault** [comment]
It is allowed in Rapido. For instance:
```
def change_title(context):
    context.content.title = "new title"
```
will work.
Note: we made nothing special regarding our usage of RestrictedPython (through zope.untrustedpython), so I do not think it is a actually prevented by RestrictedPython. Why do you think it is ?
