### ISSUE TITLE
Don't show the Chart Pie using D3js library from the tutorial source code

### ISSUE THREAD

**Issue by macagua** [collective/rapido.plone#30]
Don't show the Chart Pie using D3js library from the tutorial source code.

The Chart Pie show in the rapido.plone tutorial look like this

![Chart Pie Screen](https://cloud.githubusercontent.com/assets/185395/24829943/f402dcec-1c49-11e7-84cc-4eb97986dc17.png)

And now my case source code following the tutorial source code look like this:

![my case source code](https://cloud.githubusercontent.com/assets/185395/24829960/402fde44-1c4a-11e7-904d-9857281732a8.png)

I added  at _Site setup > HTML Filtering Settings > Custom tags_  the followings tags:
*  svg
*  g
*  path
*  text

My Plone settings:

*    Plone 5.0.7 (5017)
*    CMF 2.2.10
*    Zope 2.13.26
*    Python 2.7.3 (default, Jun 20 2016, 16:18:47) [GCC 4.7.2]
*    PIL 3.4.2 (Pillow)

Any idea?

**Comment by macagua** [comment]
@ebrehault can help me with this example, to make works fine this last practice of this tutorial? at the moment don't work!

**Comment by ebrehault** [comment]
The d3.json results processing was wrong, and we were returning an empty array.
It is fixed.

**Comment by macagua** [comment]
@ebrehault thanks you very much!!!
