### ISSUE TITLE
Enable Spanish translation docs from ReadTheDocs

### ISSUE THREAD

**Issue by macagua** [collective/rapido.plone#33]
@ebrehault the Spanish translation documentation [0] for Rapido is done!

Then I would like to add the Spanish language as a link to consult from the Rapido main page documentation.

Please can enable the Spanish translation documentation [0] from ReadTheDocs.org, if you following "Localization of Documentation guide for Project with multiple translations" [1] you need define in the "Rapido project Translations page" [2], that "rapidoplone-spanish" is a translation for your project.

[0] http://rapidoplone-spanish.readthedocs.io/es/latest/
[1] http://docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations
[2] https://readthedocs.org/dashboard/rapidoplone/translations/

**Comment by ebrehault** [comment]
I have just done that (but it does not seem to work for now, the "es" link goes to http://rapidoplone.readthedocs.io/es/latest/ , maybe we need to wait until it is active...)

**Comment by macagua** [comment]
@ebrehault really thanks! you!! :dancer:
